server:
  port: ${SPRING_SERVER_PORT:9999}

datasource:
  # 控制使用哪种数据库连接池
  useHikari: true
  hikari:
    one:
      jdbcUrl: ${SPRING_DATASOURCE_URL_1:jdbc:mysql://localhost:3306/seq?verifyServerCertificate=false&useSSL=true}
      username: ${SPRING_DATASOURCE_USERNAME:root}
      password: ${SPRING_DATASOURCE_PASSWORD:123456}
      connectionTimeout: 1000
      minIdle: 20
      maxPoolSize: 20

    two:
      jdbcUrl: ${SPRING_DATASOURCE_URL_2:jdbc:mysql://localhost:3307/seq?verifyServerCertificate=false&useSSL=true}
      username: ${SPRING_DATASOURCE_USERNAME:root}
      password: ${SPRING_DATASOURCE_PASSWORD:123456}
      connectionTimeout: 1000
      minIdle: 20
      maxPoolSize: 20

  druid:
    one:
      driver-class-name: com.mysql.jdbc.Driver
      url: ${SPRING_DATASOURCE_URL_1:jdbc:mysql://localhost:3306/seq?verifyServerCertificate=false&useSSL=true}
      username: ${SPRING_DATASOURCE_USERNAME:root}
      password: ${SPRING_DATASOURCE_PASSWORD:123456}
      testOnBorrow: true
      validationQuery: select 1
      maxActive: 100
      maxWait: 3000

      removeAbandoned: false
    two:
      driver-class-name: com.mysql.jdbc.Driver
      url: ${SPRING_DATASOURCE_URL_2:jdbc:mysql://localhost:3307/seq?verifyServerCertificate=false&useSSL=true}
      username: ${SPRING_DATASOURCE_USERNAME:root}
      password: ${SPRING_DATASOURCE_PASSWORD:123456}
      testOnBorrow: true
      validationQuery: select 1
      maxActive: 100
      removeAbandoned: false
      maxWait: 3000

dubbo:
  application:
    name: seq-provider
    logger: slf4j
  protocol:
    name: tri
    #    http dubbo共用接口
    port: ${REST_DUBBO_API_PORT:11111}
  registry:
    #    id: zk-registry
    address: ${CURATOR_CONNECTSTRING:localhost:2181}
    # This will enable application-level service discovery only (the recommended service discovery method for Dubbo3).
    # For users upgrading from Dubbo2.x, please set the value to 'all' for smooth migration.
    register-mode: instance

#curator配置
curator:
  connectString: ${CURATOR_CONNECTSTRING:localhost:2181} # zookeeper 地址
  path: seq
  retryCount: 3 # 重试次数
  elapsedTimeMs: 2000 # 重试间隔时间
  sessionTimeoutMs: 120000 # session超时时间
  connectionTimeoutMs: 15000 # 连接超时时间